# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 15:06

from __future__ import unicode_literals

import json
import os

from django.db import migrations

def forwards(apps, schema_editor):
    filepath = 'polls_app/polls.json'
    Poll = apps.get_model('polls_app','Poll')

    with open(filepath) as fp:
        contents = fp.read()
        data = json.loads(contents)
        for poll in data:
            poll_instance = Poll
            for question in data['question']:
                question_instance = Questin.objects.create(choice_text = question['questionName'])
                for option in question['options']:
                    question_instance.choices_set.create(name=option)
                poll.question.add(question_instance)

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
    migrations.RunMigration(forward,backward)
    ]
